kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${NAME}${SUFFIX}-deployment-template
  annotations:
    description: Deployment template for a django server connected to a PostGreSQL database.
    tags: django
    iconClass: icon-python
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      annotations:
        description: Defines how to deploy the application server
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}${SUFFIX}
            from:
              kind: ImageStreamTag
              namespace: ${IMAGE_NAMESPACE}
              name: ${SOURCE_IMAGE_NAME}:${IMAGE_TAG_NAME}
        - type: ConfigChange
      replicas: 0
      selector:
        name: ${NAME}${SUFFIX}
      template:
        metadata:
          name: ${NAME}${SUFFIX}
          labels:
            name: ${NAME}${SUFFIX}
            app: ${APP_NAME}${SUFFIX}
            app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
            app-group: ${APP_GROUP}
            role: ${ROLE}
            env: ${TAG_NAME}
        spec:
          containers:
            - name: ${NAME}${SUFFIX}
              image: " "
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                failureThreshold: 5
                periodSeconds: 30
                initialDelaySeconds: 3
                timeoutSeconds: 40
                httpGet:
                  path: /health
                  port: 8080
              livenessProbe:
                failureThreshold: 5
                periodSeconds: 60
                initialDelaySeconds: 30
                timeoutSeconds: 40
                httpGet:
                  path: /health
                  port: 8080
              env:
                - name: APP_FILE
                  value: ${APP_FILE}
                - name: APP_CONFIG
                  value: ${APP_CONFIG}
                - name: APP_MODULE
                  value: ${APP_MODULE}
                - name: DATABASE_SERVICE_NAME
                  value: ${DATABASE_SERVICE_NAME}${INDEXING_SUFFIX}
                - name: DATABASE_ENGINE
                  value: ${DATABASE_ENGINE}
                - name: DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: ${DATABASE_SERVICE_NAME}${CREDENTIAL_SUFFIX}
                      key: database-name
                - name: DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${DATABASE_SERVICE_NAME}${CREDENTIAL_SUFFIX}
                      key: database-user
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${DATABASE_SERVICE_NAME}${CREDENTIAL_SUFFIX}
                      key: database-password
                - name: DEMO_SITE
                  value: ${DEMO_SITE}
                - name: DJANGO_SECRET_KEY
                  value: ${DJANGO_SECRET_KEY}
                - name: DJANGO_DEBUG
                  value: ${DJANGO_DEBUG}
                - name: DJANGO_LOG_LEVEL
                  value: ${DJANGO_LOG_LEVEL}
                - name: SOLR_SERVICE_NAME
                  value: ${SOLR_SERVICE_NAME}${SUFFIX}
                - name: SOLR_CORE_NAME
                  value: ${SOLR_CORE_NAME}
                - name: SKIP_INDEXING_ON_STARTUP
                  value: ${SKIP_INDEXING_ON_STARTUP}
                - name: THEME
                  value: ${THEME}
                - name: TRACE_EVENTS
                  value: ${TRACE_EVENTS}
                - name: RECORD_TIMINGS
                  value: ${RECORD_TIMINGS}
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}

  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      annotations:
        description: Exposes and load balances the application pods
        service.alpha.openshift.io/dependencies: '[{"name": "${DATABASE_HOST}", "kind": "Service"},{"name": "${SOLR_HOST}", "kind": "Service"}]'
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        name: ${NAME}${SUFFIX}



parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the server instance.
    required: true
    value: offline-indexer
  - name: ROLE
    displayName: Role
    description: Service Role
    required: true
    value: offline-indexer
  - name: SUFFIX
    displayName: Suffix
    description: A name suffix used for all objects
    required: false
    value: -oli
  - name: INDEXING_SUFFIX
    displayName: Indexing Suffix
    description: A suffix of the services to which the indexer will connect.
    required: false
    value: -oli
  - name: CREDENTIAL_SUFFIX
    displayName: Credential Suffix
    description: A name suffix used for linking credentials.
    required: false
    value: -bc
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: Offline-Indexing
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: offline-indexing
  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description: The namespace of the OpenShift project containing the imagestream for the application.
    value: 8ad0ea-tools
  - name: DATABASE_SERVICE_NAME
    displayName: Database Service Name
    description: The name of the database server/service.
    required: true
    value: db
  - name: DATABASE_ENGINE
    displayName: Database Engine
    required: true
    description: "Database engine: postgresql, mysql, or sqlite (default)."
    value: postgresql
  - name: DATABASE_NAME
    displayName: Database Name
    required: true
    description: Name of the deployed database (see environment variables in deployed database).
    value: OrgBook
  - name: APP_FILE
    displayName: Application File
    description: Used to run the application from a Python script. This should be a path to a Python file (defaults to app.py unless set to null) that will be passed to the Python interpreter to start the application (optional).
    required: false
    value: app-vonx.py
  - name: APP_CONFIG
    displayName: Application Configuration File Path
    description: Relative path to Gunicorn configuration file (optional).
    required: false
    value: ""
  - name: APP_MODULE
    displayName: Application Module
    description: The python module for application startup.
    required: false
    value: api_indy.tob_anchor.boot:init_app
  - name: DJANGO_SECRET_KEY
    displayName: Django Secret Key
    description: Set this to a long random string.
    generate: expression
    from: '[\w]{50}'
  - name: DJANGO_DEBUG
    displayName: Django Debug
    description: If Django is in debug mode
    required: true
    value: "False"
  - name: DJANGO_LOG_LEVEL
    displayName: Django Logging Level
    description: Django logging level.
    required: true
    value: WARN
  - name: SOLR_SERVICE_NAME
    displayName: SOLR Service Name
    description: The name of the service associated with the SOLR search engine.
    required: false
    value: search-engine
  - name: SOLR_CORE_NAME
    displayName: SOLR Core Name
    description: The name of the core to use when connecting with SOLR.
    required: false
    value: credential_registry
  - name: SKIP_INDEXING_ON_STARTUP
    displayName: Skip Indexing On Startup
    description: Set this flag to `true` to skip indexing on startup as part of the database migration; set to `all` to skip indexing and suggester build, set to `false` otherwise.  When there are a large number of records to index, indexing at startup can cause startup delays and issues.
    required: true
    value: all
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the image to use for this resource.
    required: true
    value: api
  - name: IMAGE_TAG_NAME
    displayName: Image TAG name
    description: Image TAG name
    required: true
    value: oli-dev
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    required: true
    value: dev
  - name: THEME
    displayName: TheOrgBook Theme
    description: The theme to use for the tob-api.  This defines which customizations to load for the application.
    required: true
    value: bcgov
  - name: TRACE_EVENTS
    displayName: Trace Events
    description: Trace events.  Enable/Disable tracing.
    required: false
    value: "false"
  - name: RECORD_TIMINGS
    displayName: Record Timings
    description: Record Timings.  Enable/Disable method timings.
    required: false
    value: "false"
  - name: DEMO_SITE
    displayName: Demo Site Flag
    description: Set to True to indicate the site is a Demo site, False otherwise.
    required: false
    value: "True"
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 10m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 300m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 10Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 256Mi
