def PIPELINE_NAME = "api"

node {
  def libConfig = load "../workspace@script/jenkins/libConfig.groovy"
}

library identifier: "${libConfig.LIB_NAME}@${libConfig.LIB_BRANCH}", 
        retriever: modernSCM(
          [$class: 'GitSCMSource',
          remote: "${libConfig.LIB_REPO}",
          branches: [[name: "*/${libConfig.LIB_BRANCH}"]]])  

node {
  def config = load "../workspace@script/jenkins/${PIPELINE_NAME}/config.groovy"

  config.BUILDS.each {
    stage("Build ${it}") {
      script {
        openshift.withCluster() {
          openshift.withProject() {
            echo "Building the ${it} image ..."
            build(openshift, "${it}", config.WAIT_TIMEOUT)
          }
        }
      }
    }
  }

  stage("Deploy ${config.DEPLOYMENT_ENVIRONMENT_TAGS[0]}") {
    script {
      deploy("${config.APP_NAME}",
             "${config.SUFFIX}",
             "${config.NAME_SPACE}",
             "${config.DEPLOYMENT_ENVIRONMENT_TAGS[0]}")
    }
  }
}