kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Build template for a django server.
    tags: django
    iconClass: icon-python
  name: ${NAME}-build-template
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
    spec:
      source:
        type: Git
        git:
          uri: ${GIT_REPO_URL}
          ref: ${GIT_REF}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ${SOURCE_IMAGE_KIND}
            name: ${DOCKER_IMAGE_REGISTRY}${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}
          env:
            - name: PIP_INDEX_URL
              value: ${PIP_INDEX_URL}
          pullSecret:
            name: ${DOCKER_PULL_CREDENTIALS}
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${OUTPUT_IMAGE_TAG}
      triggers:
        - type: ConfigChange
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.  You should keep this as default unless your know what your doing.
    required: true
    value: api
  - name: SUFFIX
    displayName: Suffix
    description: A name suffix used for all objects
    required: false
    value: -bc
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: orgbook
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: aries-vcr
  - name: GIT_REPO_URL
    displayName: Git Repo URL
    description: The URL to your GIT repo, don't use the this default unless your just experimenting.
    required: true
    value: https://github.com/bcgov/aries-vcr.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: master
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: true
    value: server/vcr-server
  - name: SOURCE_IMAGE_KIND
    displayName: Source Image Kind
    required: true
    description: The 'kind' (type) of the  source image; typically ImageStreamTag, or DockerImage.
    value: DockerImage
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    required: true
    description: The name of the source image.
    value: bcgovimages/von-image
  - name: SOURCE_IMAGE_TAG
    displayName: Source Image Tag
    required: true
    description: The tag of the source image.
    value: py36-1.7-ew-0-s2i
  - name: PIP_INDEX_URL
    displayName: Custom PyPi Index URL
    description: The custom PyPi index URL
    value: ""
  - name: DOCKER_IMAGE_REGISTRY
    displayName: Docker Image Registry
    description: The name of the Docker image registry.
    required: false
    value: docker-remote.artifacts.developer.gov.bc.ca/
  - name: DOCKER_PULL_CREDENTIALS
    displayName: Docker Pull Credentials
    description: The name of the secret that will be used to authenticate with the Docker image registry.
    required: false
    value: docker-pull-secret
  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest
