kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: Deployment template for a postgresql server with persistent storage.
    tags: ${NAME}${SUFFIX}
  name: ${NAME}${SUFFIX}-persistent-template
objects:

  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        env: ${TAG_NAME}
    spec:
      description: |
        Allow the agent(s) to access the wallet.
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  role: ${AGENT_ROLE}
                  app: ${APP_NAME}${SUFFIX}
                  env: ${TAG_NAME}
              namespaceSelector:
                matchLabels:
                  name: ${NAMESPACE}
                  environment: ${TAG_NAME}
            - podSelector:
                matchLabels:
                  role: ${BACKUP_ROLE}
                  app: ${BACKUP_APP_NAME}${BACKUP_SUFFIX}
                  env: ${TAG_NAME}
              namespaceSelector:
                matchLabels:
                  name: ${NAMESPACE}
                  environment: ${TAG_NAME}
            - podSelector:
                matchLabels:
                  role: ${AUDIT_ROLE}
                  app: ${AUDIT_APP_NAME}${AUDIT_APP_SUFFIX}
                  env: ${TAG_NAME}
              namespaceSelector:
                matchLabels:
                  name: ${MONITORING_SERVICES_NAMESPACE}
                  environment: ${TAG_NAME}
          ports:
            - protocol: TCP
              port: 5432
      podSelector:
        matchLabels:
          role: ${ROLE}
          app: ${APP_NAME}${SUFFIX}
          env: ${TAG_NAME}


  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: ${NAME}${SUFFIX}
      generation: 1
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      strategy:
        type: Recreate
      replicas: 1
      test: false
      selector:
        matchLabels:
          name: ${NAME}${SUFFIX}
      template:
        metadata:
          labels:
            name: ${NAME}${SUFFIX}
            app: ${APP_NAME}${SUFFIX}
            app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
            app-group: ${APP_GROUP}
            role: ${ROLE}
            env: ${TAG_NAME}
        spec:
          volumes:
            - name: ${NAME}${SUFFIX}-data
              persistentVolumeClaim:
                claimName: ${NAME}${SUFFIX}
            - name: ${NAME}${SUFFIX}-logging-config-volume
              configMap:
                name: ${LOGGING_CONFIG_MAP_NAME}
                items:
                  - key: ${LOGGING_CONFIG_FILE_NAME}
                    path: ${LOGGING_CONFIG_FILE_NAME}
            - name: ${NAME}${SUFFIX}-autovacuum-config-volume
              configMap:
                name: ${AUTOVACUMM_CONFIG_MAP_NAME}
                items:
                  - key: ${AUTOVACUMM_CONFIG_FILE_NAME}
                    path: ${AUTOVACUMM_CONFIG_FILE_NAME}
          containers:
            - name: ${NAME}${SUFFIX}
              image: image-registry.openshift-image-registry.svc:5000/${IMAGE_NAMESPACE}/${SOURCE_IMAGE_NAME}:${TAG_NAME}
              ports:
                - containerPort: 5432
                  protocol: TCP
              env:
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${CREDENTIAL_SUFFIX}
                      key: database-user
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${CREDENTIAL_SUFFIX}
                      key: database-password
                - name: POSTGRESQL_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${CREDENTIAL_SUFFIX}
                      key: admin-password
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${CREDENTIAL_SUFFIX}
                      key: database-name
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              volumeMounts:
                - name: ${NAME}${SUFFIX}-data
                  mountPath: ${MOUNT_PATH}
                - name: ${NAME}${SUFFIX}-logging-config-volume
                  mountPath: ${LOGGING_CONFIG_MOUNT_PATH}${LOGGING_CONFIG_FILE_NAME}
                  subPath: ${LOGGING_CONFIG_FILE_NAME}
                - name: ${NAME}${SUFFIX}-autovacuum-config-volume
                  mountPath: ${AUTOVACUMM_CONFIG_MOUNT_PATH}${AUTOVACUMM_CONFIG_FILE_NAME}
                  subPath: ${AUTOVACUMM_CONFIG_FILE_NAME}
              livenessProbe:
                tcpSocket:
                  port: 5432
                initialDelaySeconds: 30
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - -i
                    - -c
                    - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'
                initialDelaySeconds: 5
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
              securityContext:
                capabilities: {}
                privileged: false
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler

  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      storageClassName: ${PERSISTENT_VOLUME_CLASS}
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: ${PERSISTENT_VOLUME_SIZE}

  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    stringData:
      admin-password: ${POSTGRESQL_ADMIN_PASSWORD}
      database-password: ${POSTGRESQL_PASSWORD}
      database-user: ${POSTGRESQL_USER}
      database-name: ${POSTGRESQL_DATABASE_NAME}
    type: Opaque
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
      annotations:
        template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
    spec:
      ports:
        - name: postgresql
          protocol: TCP
          port: 5432
          targetPort: 5432
      selector:
        matchLabels:
          name: ${NAME}${SUFFIX}
      type: ClusterIP
      sessionAffinity: None

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the server instance.
    required: true
    value: wallet

  - name: ROLE
    displayName: Role
    description: Role
    required: true
    value: wallet
  - name: AGENT_ROLE
    displayName: Agent Role
    description: Agent Role
    required: true
    value: agent
  - name: BACKUP_ROLE
    displayName: Backup Role
    description: Backup Role
    required: true
    value: backup
  - name: BACKUP_APP_NAME
    displayName: Backup App Name
    description: The App Name associated with the backup container.
    required: true
    value: Backup
  - name: BACKUP_SUFFIX
    displayName: Backup App Suffix
    description: The suffix of the Backup App, this could be different then SUFFIX.
    required: true
    value: -bc

  - name: AUDIT_ROLE
    displayName: Audit Role
    description: Audit Role
    required: true
    value: audit
  - name: AUDIT_APP_NAME
    displayName: Audit App Name
    description: Audit App Name
    required: true
    value: Audit
  - name: AUDIT_APP_SUFFIX
    displayName: Audit App Suffix
    description: Audit App Suffix
    required: false
    value:

  - name: MONITORING_SERVICES_NAMESPACE
    displayName: The namespace of the monitoring resources.
    required: true
    value: ca7f8f

  - name: NAMESPACE
    displayName: The target namespace for the resources.
    required: true
    value: 8ad0ea
  - name: SUFFIX
    displayName: Suffix
    description: A name suffix used for all objects
    required: false
    value: -bc
  - name: CREDENTIAL_SUFFIX
    displayName: Credential Suffix
    description: A name suffix used for linking credentials.
    required: false
    value: -bc

  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: orgbook
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: aries-vcr
  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description: The namespace of the OpenShift project containing the imagestream for the application.
    value: 8ad0ea-tools
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the image to use for this resource.
    required: true
    value: db
  - name: IMAGE_TAG_NAME
    displayName: Image TAG name
    description: Image TAG name
    required: true
    value: dev
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    required: true
    value: dev
  - name: POSTGRESQL_DATABASE_NAME
    displayName: PostgreSQL Database Name
    description: The name of the PostgreSQL database.
    required: true
    value: default_wallet
  - name: POSTGRESQL_USER
    displayName: PostgreSQL Connection Username
    description: Username for PostgreSQL user that will be used for accessing the database.  Needs to be basee64 encoded/
    required: true
    generate: expression
    from: "[a-zA-Z_][a-zA-Z0-9_]{10}"
  - name: POSTGRESQL_PASSWORD
    displayName: PostgreSQL Connection Password
    description: Password for the PostgreSQL connection user.  Needs to be basee64 encoded/
    required: true
    generate: expression
    from: "[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]{16}"
  - name: POSTGRESQL_ADMIN_PASSWORD
    displayName: PostgreSQL Admin Password
    description: Password for the 'postgres' PostgreSQL administrative account.  Needs to be basee64 encoded.
    required: true
    generate: expression
    from: "[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]{16}"
  - name: MOUNT_PATH
    displayName: Mount Path
    description: The path to mount the persistent volume.
    required: true
    value: /var/lib/pgsql/data
  - name: PERSISTENT_VOLUME_SIZE
    displayName: Persistent Volume Size
    description: The size of the persistent volume , e.g. 512Mi, 1Gi, 2Gi.
    required: true
    value: 200Gi
  - name: PERSISTENT_VOLUME_CLASS
    displayName: Persistent Volume Class name
    description: The class of the volume; netapp-block-standard, netapp-block-standard, netapp-file-extended, or netapp-block-extended.
    required: false
    value: netapp-block-standard

  # ===============================================================================
  # Postgres Database Configuration
  #--------------------------------------------------------------------------------
  - name: LOGGING_CONFIG_FILE_NAME
    displayName: Config File Name
    description: The name of the configuration file.
    required: true
    value: logging.conf
  - name: LOGGING_CONFIG_MAP_NAME
    displayName: Config Map Name
    description: The name of the configuration map.
    required: true
    value: wallet-logging-conf-bc
  - name: LOGGING_CONFIG_MOUNT_PATH
    displayName: Config Mount Path
    description: The path to use to mount the config file.
    required: true
    value: /opt/app-root/src/postgresql-cfg/
  - name: AUTOVACUMM_CONFIG_FILE_NAME
    displayName: Config File Name
    description: The name of the configuration file.
    required: true
    value: autovacuum.conf
  - name: AUTOVACUMM_CONFIG_MAP_NAME
    displayName: Config Map Name
    description: The name of the configuration map.
    required: true
    value: wallet-autovacuum-conf-bc
  - name: AUTOVACUMM_CONFIG_MOUNT_PATH
    displayName: Config Mount Path
    description: The path to use to mount the config file.
    required: true
    value: /opt/app-root/src/postgresql-cfg/
  # ===============================================================================

  # ===============================================================================
  # Resource Allocation
  #--------------------------------------------------------------------------------
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 10m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 4000m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 10Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 8000Mi
  # ===============================================================================
