def PIPELINE_NAME = "agent"

node {

  def config = load "../workspace@script/jenkins/${PIPELINE_NAME}/config.groovy"
  def utils = load "../workspace@script/jenkins/utils.groovy"

  config.BUILDS.each {
    stage("Build ${it}") {
      script {
        openshift.withCluster() {
          openshift.withProject() {
            echo "Building the ${it} image ..."
            utils.build("${it}", config.WAIT_TIMEOUT)
          }
        }
      }
    }
  }

  stage("Deploy ${config.DEPLOYMENT_ENVIRONMENT_TAGS[0]}") {
    script {
      utils.deploy("${config.APP_NAME}",
                  "${config.SUFFIX}",
                  "${config.NAME_SPACE}",
                  "${config.DEPLOYMENT_ENVIRONMENT_TAGS[0]}")
    }
  }
}