kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: Deployment template for a angular on nginx
    tags: angular,nginx
  name: ${NAME}
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${NAME}${SUFFIX}-allow-ingress
      labels:
        name: ${NAME}${SUFFIX}-allow-ingress
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      description: |
        Allow traffic from routes into the ${ROLE} container(s).
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      podSelector:
        matchLabels:
          role: ${ROLE}
          app: ${APP_NAME}${SUFFIX}
          env: ${TAG_NAME}
      policyTypes:
        - Ingress

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      creationTimestamp: null
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
      name: ${NAME}${SUFFIX}
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: ${NAME}${SUFFIX}
      strategy:
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            name: ${NAME}${SUFFIX}
            app: ${APP_NAME}${SUFFIX}
            app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
            app-group: ${APP_GROUP}
            role: ${ROLE}
            env: ${TAG_NAME}
  
        spec:
          volumes:
            - name: ${NAME}${SUFFIX}-caddy-config-volume
              configMap:
                name: ${NAME}-${CADDY_CONFIG_MAP_NAME}${SUFFIX}
                items:
                  - key: ${CADDY_CONFIG_FILE_NAME}
                    path: ${CADDY_CONFIG_FILE_NAME}
          containers:
            - image: image-registry.openshift-image-registry.svc:5000/${IMAGE_NAMESPACE}/${NAME}:${TAG_NAME}
              imagePullPolicy: Always
              name: ${NAME}${SUFFIX}
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: WEB_HOST_NAME
                  value: ${WEB_HOST_NAME}
                - name: WEB_HOST_PORT
                  value: ${WEB_HOST_PORT}
                - name: WEB_HOST_TLS
                  value: ${WEB_HOST_TLS}
                - name: API_HOST
                  value: ${API_HOST}${SUFFIX}
                - name: API_PORT
                  value: ${API_PORT}
                - name: VC_SERVICE_HOST
                  value: ${VC_SERVICE_HOST}${SUFFIX}
                - name: VC_SERVICE_PORT
                  value: ${VC_SERVICE_PORT}

                - name: RATE_LIMIT_ORDERING
                  value: ${RATE_LIMIT_ORDERING}
                - name: DEFAULT_RATE_LIMIT
                  value: ${DEFAULT_RATE_LIMIT}
                - name: API_RATE_LIMIT
                  value: ${API_RATE_LIMIT}

                - name: TRUSTED_PROXIES
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: trusted_proxies
                - name: BLOCK_LIST
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: block_list
                - name: USER_AGENT_REGEX
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: user_agent_regex
                - name: FILTER_EXPRESSION
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: filter_expression
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              volumeMounts:
                - name: ${NAME}${SUFFIX}-caddy-config-volume
                  mountPath: ${CADDY_CONFIG_MOUNT_PATH}${CADDY_CONFIG_FILE_NAME}
                  subPath: ${CADDY_CONFIG_FILE_NAME}
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                timeoutSeconds: 60
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                timeoutSeconds: 60
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    stringData:
      trusted_proxies: ${TRUSTED_PROXIES}
      block_list: ${BLOCK_LIST}
      user_agent_regex: ${USER_AGENT_REGEX}
      filter_expression: ${FILTER_EXPRESSION}
    type: Opaque

  - kind: Service
    apiVersion: v1
    metadata:
      creationTimestamp: null
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
      name: ${NAME}${SUFFIX}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        matchLabels:
          name: ${NAME}${SUFFIX}
      sessionAffinity: None
      type: ClusterIP

  - kind: Route
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
      annotations:
        haproxy.router.openshift.io/timeout: ${ROUTE_TIMEOUT}
    spec:
      host: ${APPLICATION_DOMAIN}
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}${SUFFIX}
        weight: 100

  - kind: HorizontalPodAutoscaler
    apiVersion: autoscaling/v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: ${NAME}${SUFFIX}
      minReplicas: ${{MIN_REPLICAS}}
      maxReplicas: ${{MAX_REPLICAS}}

parameters:
  - description: The name assigned to all of the openshift objects defined in this template. It is also the name of runtime image you want.
    displayName: Name
    name: NAME
    required: true
    value: frontend
  - name: ROLE
    displayName: Role
    description: Service Role
    required: true
    value: frontend
  - name: API_ROLE
    displayName: Api Role
    description: Api Role
    required: true
    value: api
  - name: NAMESPACE
    displayName: The target namespace for the resources.
    required: true
    value: 8ad0ea
  - name: SUFFIX
    displayName: Suffix
    description: A name suffix used for all objects
    required: false
    value: -bc
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: orgbook
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: aries-vcr
  - description: The namespace where to get the above image name
    displayName: Image Namespace
    name: IMAGE_NAMESPACE
    required: true
    value: 8ad0ea-tools

  - name: WEB_HOST_NAME
    displayName: Web HOST
    description: The hostname of the web service.
    required: false
    value:
  - name: WEB_HOST_PORT
    displayName: Web Host Port
    description: The port number on which the web service is listening.
    required: true
    value: "8080"
  - name: WEB_HOST_TLS
    displayName: Web Host TLS
    description: The TLS setting ('on', or 'off') for the web service.
    required: true
    value: "off"
  - name: API_HOST
    displayName: API HOST
    description: The hostname of the api service.
    required: true
    value: api
  - name: API_PORT
    displayName: API Port
    description: The port number on which the api is listening.
    required: true
    value: "8080"
  - name: VC_SERVICE_HOST
    displayName: VC SERVICE HOST
    description: The hostname of the VC service.
    required: true
    value: vc-service
  - name: VC_SERVICE_PORT
    displayName: VC SERVICE Port
    description: The port number on which the VC service is listening.
    required: true
    value: "8080"

  - name: RATE_LIMIT_ORDERING
    displayName: Rate Limit Ordering
    description: The directive defining where to order the rate limiter.
    required: false
    value:
  - name: DEFAULT_RATE_LIMIT
    displayName: Default Rate Limit
    description: The default rate limit for the server.
    required: false
    value:
  - name: API_RATE_LIMIT
    displayName: API Rate Limit
    description: The rate limit for API calls.
    required: false
    value:

  - name: CADDY_CONFIG_FILE_NAME
    displayName: Config File Name
    description: The name of the configuration file.
    required: true
    value: Caddyfile
  - name: CADDY_CONFIG_MAP_NAME
    displayName: Config Map Name
    description: The name of the configuration map.
    required: true
    value: caddy-conf
  - name: CADDY_CONFIG_MOUNT_PATH
    displayName: Config Mount Path
    description: The path to use to mount the config file.
    required: true
    value: /etc/caddy/

  - name: TRUSTED_PROXIES
    displayName: Trusted Proxies
    description: The list of trusted proxies for the frontend.
    required: true
    value:
  - name: BLOCK_LIST
    displayName: Block List
    description: The list of IP addresses to block at the frontend.
    required: true
    value:
  - name: USER_AGENT_REGEX
    displayName: User Agent Regex
    description: The regex to use to identify user agents to block.
    required: true
    value:
  - name: FILTER_EXPRESSION
    displayName: Filter Expression
    description: The expression to use for filtering requests.
    required: true
    value:

  - name: APPLICATION_DOMAIN
    displayName: Application Hostname
    description: The exposed hostname that will route to the service, e.g., myappname.apps.silver.devops.gov.bc.ca, if left blank a value will be defaulted.
    value: dev.orgbook.gov.bc.ca
  - name: ROUTE_TIMEOUT
    displayName: Route Timeout
    description: The timeout for the application route.  When this timeout is exceeded the application's route will respond with a 504 Gateway Timeout error.
    required: true
    value: 120s
  - description: The TAG name for this environment, e.g., dev, test, prod
    displayName: Env TAG name
    name: TAG_NAME
    value: dev

  - name: MIN_REPLICAS
    displayName: Minimum Replicas
    description: The minimum number of pods to have running.
    required: true
    value: "3"
  - name: MAX_REPLICAS
    displayName: Maximum Replicas
    description: The maximum number of pods to have running.
    required: true
    value: "6"

  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 10m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 250m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 100Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 256Mi
